### ISSUE TITLE
Error in docker `compose.tml`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#359]
Hi @da2ce7 I think there is a copy/paste error in the docker `compose.yaml`file, right?

https://github.com/torrust/torrust-index/blob/develop/compose.yaml#L4C1-L22C14

```yaml
  index:
    image: torrust-index:release
    tty: true
    environment:
      - TORRUST_INDEX_CONFIG=${TORRUST_TRACKER_CONFIG}
      - TORRUST_INDEX_DATABASE_DRIVER=${TORRUST_TRACKER_DATABASE_DRIVER:-sqlite3}
      - TORRUST_INDEX_TRACKER_API_TOKEN=${TORRUST_INDEX_TRACKER_API_TOKEN:-MyAccessToken}
    networks:
      - server_side
    ports:
      - 3001:3001
    volumes:
      - ./storage/tracker/lib:/var/lib/torrust/index:Z
      - ./storage/tracker/log:/var/log/torrust/index:Z
      - ./storage/tracker/etc:/etc/torrust/index:Z
    depends_on:
      - tracker
      - mailcatcher
      - mysql
```

Env vars should be:

```
      - TORRUST_INDEX_CONFIG=${TORRUST_INDEX_CONFIG}
      - TORRUST_INDEX_DATABASE_DRIVER=${TORRUST_INDEX_DATABASE_DRIVER:-sqlite3}
      - TORRUST_INDEX_TRACKER_API_TOKEN=${TORRUST_INDEX_TRACKER_API_TOKEN:-MyAccessToken}
```

And also volumes:

```
      - ./storage/index/lib:/var/lib/torrust/index:Z
      - ./storage/index/log:/var/log/torrust/index:Z
      - ./storage/index/etc:/etc/torrust/index:Z
```

cc @mario-nt
