### ISSUE TITLE
Allow to overwrite the auth `secret_key = "MaxVerstappenWC2021"` with env var

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#412]
In the `auth` config section you need to define a secret:

```toml
[auth]
email_on_signup = "Optional"
min_password_length = 6
max_password_length = 64
secret_key = "MaxVerstappenWC2021"
```

Allow to overwrite it with an env var like the `TORRUST_INDEX_TRACKER_API_TOKEN`

```toml
# Please override the tracker token setting the
#    `TORRUST_INDEX_TRACKER_API_TOKEN`
#                     environmental variable!
```

The name could be `TORRUST_INDEX_AUTH_SECRET_KEY`. 

In general env vars could be like `TORRUST_CONFIG_SECTION_VAR_NAME`.

- Prefix: `TORRUST_INDEX_`
- Configuration section: `AUTH`, `DATABASE`, `WEBSITE`, `TRACKER`, `NET`, ...
- Config option in uppercase: `SECRET_KEY`
