### ISSUE TITLE
 Mitigate the risk of information leakage through sign-up forms

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#507]
When you use an email that has already been used by another user you get a message like this:

![image](https://github.com/torrust/torrust-index/assets/58816/a1d6f8ee-55ba-4b6e-b92a-c91e03c79ed7)

That allows users to easily check is a user with a given email is registered. Although this is very common behavior in a lot of online services, for example, LinkedIn:

![image](https://github.com/torrust/torrust-index/assets/58816/b757e899-a43f-42c6-b970-d833ced6f6d8)

I think we should try to mitigate it.

### Proposal 1

Add a captcha and/or a rate limit (IP) to the registration form to at least make it harder to automatize checking a list of emails.

### Proposal 2

- Make the email always optional in the sign-up form.
- Remove configuration option `email_on_signup`. The email would be always optional.
- Allow email duplicates. You can sign up with somebody else's email.
- The application does nothing with the user's email unless is validated. This should be always the case. For example, to reset passwords, send notifications, etc. For the time being, the email is only verified when `email_verification_enabled` option is enabled. The user's email is not used for anything else.

```toml
# ...

[auth]
email_on_signup = "Optional"

# ...

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
username = ""
password = ""
server = ""
port = 25

# ...
````

cc @torrust/torrustaceans
