### ISSUE TITLE
Update tracker configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#648]
Relates to: https://github.com/torrust/torrust-tracker/issues/401

New breaking changes have been applied to the Tracker configuration.

- Renamed `log_level` to  `threshold`.
- Tracker mode split into `listed` and `private` flags.
- Added configuration `version`.

From:

```toml
[logging]
log_level = "info"

[core]
mode = "public"
tracker_usage_statistics = true
inactive_peer_cleanup_interval = 600

# ...
```

To:

```toml
version = "2"

[logging]
threshold = "info"

[core]
inactive_peer_cleanup_interval = 600
listed = false
private = false
tracker_usage_statistics = true

# ...
```

**NOTE**: unchanged fields are omitted.
