### ISSUE TITLE
Configuration overhaul: rename `log_level` to `threshold`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#652]
Parent issue: https://github.com/torrust/torrust-index/issues/591

Rename `log_level` to `threshold`

```toml
[logging]
log_level = "info"
```

```toml
[logging]
threshold = "info"
```
