### ISSUE TITLE
Configuration overhaul: rename `auth::secret_key` to `auth::user_claim_token_pepper`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#653]
Parent issue: https://github.com/torrust/torrust-index/issues/591

Rename `auth::secret_key` to `auth::password_database_pepper`

```toml
[auth]
secret_key = "MaxVerstappenWC2021"
```

```toml
[auth]
password_database_pepper = "MaxVerstappenWC2021"
```

Hi @da2ce7, the other day, when we decided to rename this field, I was wrong; the `secret_key` is only used to encode/decode (encrypt/decrypt) the JSON web token. We are using a HMAC secret that is not base64.

It's not used to encrypt database data. We are using [MCF](https://passlib.readthedocs.io/en/stable/modular_crypt_format.html).

Currently, we support:

- [argon2](https://passlib.readthedocs.io/en/stable/lib/passlib.hash.argon2.html#passlib.hash.argon2)
- [pbkdf2_sha256](https://passlib.readthedocs.io/en/stable/lib/passlib.hash.pbkdf2_digest.html#passlib.hash.pbkdf2_sha256)

Should we use a different name @da2ce7? I mean, I don't think `password_database_pepper` makes sense.
