### ISSUE TITLE
Configuration overhaul: make mail-related configuration clearer

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#654]
Parent issue: https://github.com/torrust/torrust-index/issues/591

Make mail-related configuration more straightforward. There are a couple of options that could be confusing: `email_on_signup` and `email_verification_enabled`.

### Current version

```toml
[auth]
email_on_signup = "optional"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
```

### New version

```toml
[registration]
# Other future options related to registration in addition to mail.
# All options related to mail go into the mail subtype.

[registration.mail]
required = true
verified = true
```

The new version adds a new section for the registration configuration. That section contains a subtype with two fields for the email:

- `required`: `true` if the email is mandatory for registration.
- `verified`: `true` if the app sends a verification email to verify the user's email.

The second one maps directly to the old field `email_verification_enabled`.

Regarding the first one `email_on_signup`, it has these values:

- `required`: the user must provide a valid email even if email verification is disabled.
- `optional`: the app shows the email field in the registration form, but the user can omit it. It can be empty. Some user's profiles may have it and others may not.
- `ignored`: the frontend app does not show the email field at all. However, the API accepts that param in the POST request but, it ignores it.

It will be simplified:

- When `required` is `true` the signup form contains the `email` field and is mandatory.
- When `required` is `false` the signup form does **NOT** contain the `email` field and is not mandatory. However in the future, the user can provide an email in the user's profile settings page.

### Notes

We have to check some invalid configurations and show an error when the application is starting.

- If `registration.mail.verified` is true, the `mail` server configuration must be provided (it can't be `None`).

**Comment by josecelano** [comment]
Hey @da2ce7, can you please review this? If we implement it as I have described it, we will remove the option to provide an email, even if it's not mandatory, until we allow it in the profile settings (new feature). 

This could be a helpful feature for some reason. I think email is the only way to communicate with users now, so even if we don't require it, it could be useful to allow the user to provide it.

**Comment by da2ce7** [comment]
@josecelano 

I would rename `mail` to `email`.

Here are the different variants. 


Registration Disabled:

```toml
# [registration]
```

Registration without email option:

```toml
[registration]
```

Registration optionally including an email address:

```toml
[registration]
[registration.email]
```

Registration with  email:

```toml
[registration]
[registration.email]
required = true
```

Registration with optional email, but if email is supplied it is verified:

```toml
[registration]
[registration.email]
verified = true
```

Registration with email and email is verified:

```toml
[registration]
[registration.email]
required = true
verified = true
```
