### ISSUE TITLE
Configuration overhaul: split `TrackerMode`into two flags `private` and `listed`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#655]
Parent issue: https://github.com/torrust/torrust-index/issues/591

Update the tracker configuration section to follow [changes in the tracker configuration](https://github.com/torrust/torrust-tracker/issues/932).

### Current config

```toml
[tracker]
mode = "public"
```

### New config

```toml
[tracker]
private = false
listed = false
```
