### ISSUE TITLE
Config overhaul: use an explicit section for metadata

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#672]
Parent issue: https://github.com/torrust/torrust-index/issues/591
Relates to: https://github.com/torrust/torrust-tracker/issues/958

After a discussion today, we decided to make the "namespace" in the configuration explicit by using the project name or package name. The main benefit is you can parse the file to know which service the configuration belongs to.

### Current version

```toml
version = "2.0.0"

# ...
```

### Proposal 1

```toml
[torrust_index]
version = "2.0.0"

# ...
```

### Proposal 2

```toml
[project]
name = "torrust_index"
version = "2.0.0"

# ...
```

**Comment by josecelano** [comment]
We will use the same format as in the Tracker: https://github.com/torrust/torrust-tracker/issues/958#issuecomment-2264909246

```toml
[metadata]
crate = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"
```
