### ISSUE TITLE
Config overhaul: make some fields mandatory

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#673]
Parent issue: https://github.com/torrust/torrust-index/issues/591

In the current version, all config values have a default value. You can run the app without providing any config value at all.

@da2ce7 suggested forcing the system admin (who is responsible for setting up the app) to provide at least some critical options like:

```toml
version = "2"

[logging]
threshold = "info"
```

They are already mandatory, but we have defined server default values, meaning you can omit the file in the TOML or JSON file, and it will use the default value. We have to remove the default values to force the users to provide the values.

Hi @da2ce7 is that list OK?

### UPDATE (2024-08-02)

The metadata section was updated. Only the `schema_version` is mandatory.

```toml
[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"
```
