### ISSUE TITLE
Config overhaul: rename config option `verified` to `verification_required`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#674]
Parent issue: https://github.com/torrust/torrust-index/issues/591

From:

```toml
[registration]

[registration.email]
required = true
verified = true
```

To: 

```toml
[registration]

[registration.email]
required = true
verification_required = true
```
