### ISSUE TITLE
Update tracker configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#696]
The [Tracker TOML configuration file has changed](https://github.com/torrust/torrust-tracker/pull/992). The following fields are now mandatory.

```toml
[metadata]
schema_version = "2.0.0"

[logging]
threshold = "info"

[core]
listed = false
private = true
```

The `[metadata]` section was added, and the `version` option was renamed to `schema_version`.
